title: "Z-Rad: The Swiss Pocket Knife for Radiomics"
logo: /figures/ZRadLogo.jpg

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

navigation:
  - title: Get Started
    url: /tabs/get_started.html
  - title: Preprocessing
    url: /tabs/resampling.html
  - title: Filtering
    url: /tabs/filtering.html
  - title: Radiomics
    url: /tabs/radiomics.html
  - title: Visualization
    url: /tabs/visualization.html
  - title: API (Advanced)
    url: /tabs/api.html
